spring:
  profiles:
    active: dev

zuul:
  ignoredServices: '*'
  routes:
    resource:
      path: /resource/**
      serviceId: resource-service
    fe:
      path: /fe/**
      serviceId: fe-service
    search:
      path: /search/**
      serviceId: search-service