eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# DB setup
spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/shop_dev
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy








