eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# DB setup
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/netgloo_blog?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy








