spring:
  profiles:
    active: dev
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
  http:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

server:
  port: 9191

eureka:
  instance:
    prefer-ip-address: true

pictures.storage: D:\me\store\microservices\pictures